### ISSUE TITLE
Unclear decription of SWC-122

### ISSUE THREAD

**Issue by eMarchenko** [SmartContractSecurity/SWC-registry#108]
Just some weird sentence in the [description](https://github.com/SmartContractSecurity/SWC-registry/blob/master/entries/SWC-122.md#description):
> In order to solve the problem implementations that assume the validity of a signed message based on other methods that do not have that barrier.

I'd like someone to improve it because I'm not sure if I understand it correctly.

**Comment by thec00n** [comment]
Closing the issue as the description should be much better now. Feel free to reopen the issue should you not agree.

**Comment by eMarchenko** [comment]
thank you, new description is much more convenient!
