### ISSUE TITLE
Unclear testcase for SWC-112

### ISSUE THREAD

**Issue by montyly** [SmartContractSecurity/SWC-registry#116]
Hi,

[SWC-112](https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-112) description states that you should not call untrusted contract with delegatecall. Its short description is: `Delegation sets target address in delegatecall() from user input`

The testcase [test_cases/delegate_call_to_untrusted_callee/delegate.sol](https://github.com/SmartContractSecurity/SWC-registry/blob/86118bc99a2d5fee639c5a8b47f6214ae1236ad9/test_cases/delegate_call_to_untrusted_callee/delegate.sol) is a bit ambigious and does not seem to fit really the description.

Here you call a destination that was added at construction. The destination cannot be changed,so it should be fine:

https://github.com/SmartContractSecurity/SWC-registry/blob/86118bc99a2d5fee639c5a8b47f6214ae1236ad9/test_cases/delegate_call_to_untrusted_callee/delegate.sol#L27-L35

But the destination has a bug that allows anyone to become the owner:

https://github.com/SmartContractSecurity/SWC-registry/blob/86118bc99a2d5fee639c5a8b47f6214ae1236ad9/test_cases/delegate_call_to_untrusted_callee/delegate.sol#L17-L19

The testcase for SWC-112 should not be rather showing an example where anyone can change the delegatecall destination?

**Comment by thec00n** [comment]
>The testcase for SWC-112 should not be rather showing an example where anyone can change the delegatecall destination

Agreed.
