### ISSUE TITLE
Include contract name in config file

### ISSUE THREAD

**Issue by alexleid** [SmartContractSecurity/SWC-registry#138]
Some of the examples seem to contain multiple contracts in the source file (e.g. [modifier_reentrancy.sol](https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/reentracy/modifier_reentrancy.sol)). Typically you have to specify which contract to verify when using automated tools, so reading the contract name from the yaml config would be very helpful.

Is there anywhere else where I can reliably find the contract name for each contract with a vulnerability? It's possible to read the file and fetch every name, but having the name on hand would be much easier.

**Comment by thec00n** [comment]
Hey @alexleid have a look at #168 this should address your question.
