### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by MatthiasEgli-chainsecurity** [SmartContractSecurity/SWC-registry#148]
Currently this project is under GPL, making it harder to use it inside other projects. Changing the license to MIT will allow those use-cases and it closely mirrors the license used for the CWE project (https://cwe.mitre.org/about/termsofuse.html).

This will need consent from the past contributors @thec00n @b-mueller @s0b0lev @Destiner @pvienhage @PumpkingWok @wuestholz @montyly @rocky @antonper @ethers @vl-ti 

Please comment on this issue with a short "Approve" from your respective github accounts.

**Comment by antonper** [comment]
Approve

**Comment by PumpkingWok** [comment]
Approve

**Comment by Destiner** [comment]
Approve

**Comment by vl-ti** [comment]
Approve

**Comment by s0b0lev** [comment]
Approve

**Comment by b-mueller** [comment]
I, Bernhard Mueller, hereby consent with the proposed amendment 
![signature](https://user-images.githubusercontent.com/5194767/49299115-89bd9980-f4f1-11e8-8c43-d41082871f3c.png)

**Comment by wuestholz** [comment]
Approve

**Comment by rocky** [comment]
approve

**Comment by rocky** [comment]
approve

**Comment by pvienhage** [comment]
Approve

**Comment by thec00n** [comment]
I have looked at the permissive licenses again and after considering them I think it’s best to choose the most permissive one. The initial objective was and is to get as many contributions as possible from the community and the MIT license wins here.

Approve.

**Comment by thec00n** [comment]
@montyly @ethers are guys ok with this as well.

**Comment by montyly** [comment]
Approve

**Comment by MatthiasEgli-chainsecurity** [comment]
In case @ethers is not responding, I can undo the only commit (https://github.com/SmartContractSecurity/SWC-registry/commit/2bb5638975b7c9a214aac8d3c17fa759ac2e8432) and we would be good to merge #149. Will do so tomorrow if there is no response until then.

**Comment by thec00n** [comment]
Hodl on @MatthiasEgli-chainsecurity, let me reach out to @ethers and give it a bit more time.

**Comment by ethers** [comment]
I don't want to hold this up and approve.  Would like to know what is the reason for MIT instead of Apache 2.0 ?

**Comment by ChainSecurityAudits** [comment]
No strong opinion, was going for the most permissive one and one which closely mirrors the license used for the CWE project (being the traditional IT security project this project is mirroring somehow). In my understanding, with MIT license anyone can release a project under Apache 2.0 using and modifying this code, while the other way round is not necessarily possible.
Now that everyone accepted MIT for SWC, it is also up to the project maintainers to change the license to a less permissive one without the need to get consent (again just afaik, not a lawyer...).

**Comment by MatthiasEgli-chainsecurity** [comment]
No strong opinion, was going for the most permissive one and one which closely mirrors the license used for the CWE project (being the traditional IT security project this project is mirroring somehow). In my understanding, with MIT license anyone can release a project under Apache 2.0 using and modifying this code, while the other way round is not necessarily possible.
Now that everyone accepted MIT for SWC, it is also up to the project maintainers to change the license to a less permissive one without the need to get consent (again just afaik, not a lawyer...).

**Comment by thec00n** [comment]
All contributors have accepted the license change, merging PR https://github.com/SmartContractSecurity/SWC-registry/pull/149
