### ISSUE TITLE
Create 3 test cases for Vyper 

### ISSUE THREAD

**Issue by thec00n** [SmartContractSecurity/SWC-registry#156]
Create 3 vulnerable test cases for Vyper with accompanying yaml configuration and link them if possible to existing SWC-definitions. The PR should be the starting point for a discussion on how other EVM based languages can be integrated in the SWC-registry and what gaps there are currently in the structure if any that should be addressed.

**Comment by thec00n** [comment]
Could you also include the json files and include all the information that the Vyper compiler generates similar to what we have currently for Solidity files.

**Comment by pvienhage** [comment]
Done, I used vyper -f combined_json filename.vy which includes the most bytecode output types I think. Let me know what you think.
