### ISSUE TITLE
Create a SWC-registry utils cli tool

### ISSUE THREAD

**Issue by thec00n** [SmartContractSecurity/SWC-registry#170]
`utils` can be used to create the following output by providing a build artefact from the Solidity compiler. 

1.) Print keccak256 hash for all bytecodes in a compile artefact e.g. https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/arbitrary_jump/FunctionTypes.json with Web3.utils.sha3() 

2.) Run geth disasm for all bytecodes in the compile artefact e.g. `echo "some bytecode" > /tmp/somebytecode | evm disasm /tmp/somebytecode`. Check if geth is installed otherwise inform the user to do so.

The output should look something like this:

Contract: FunctionTypes.sol:FunctionTypes
Creation Bytecode: 608060405260003414 ... 
Keccak256 Hash: 0xe4e2af1f7f7177c7423a7eb71344a8dc203938a1a538e5ea8552974833aee820
Disassembly:
000000: PUSH1 0x80
000002: PUSH1 0x40
000004: MSTORE
000005: PUSH1 0x04
000007: CALLDATASIZE
000008: LT
000009: PUSH2 0x0041
000012: JUMPI
... 
Runtime Bytecode: 608060405260043610 ...
Keccak256 Hash: 0x10262f9b836c8ce4a7c2807a00b08e278094414ceeb2b5cbf4365c7ced0fd2f9
Disassembly:
...

**Comment by PumpkingWok** [comment]
Hi @thec00n,
Would you like that i develop it using a scripting language like shell or python ?
Do I need to check that `geth` is running other than it has installed, right ? for using `Web3` functions.
Thanks in advance.

**Comment by thec00n** [comment]
Thanks for clarifying, I would prefer JS. 
Yeah just check if `evm` is there and if not inform the user that it should be installed.

**Comment by PumpkingWok** [comment]
Hi @thec00n,
I'm going to open a PR tomorrow, I have developed a js script with a structure similar to those into `scripts`. Could it be ok for you ?
Would you like that the tool handle the error in `evm disasm` ? Some times `evm` retrieves an error regard `incomplete push instruction`.
Thanks

**Comment by PumpkingWok** [comment]
Hi @thec00n,

It seems that `evm disasm` has some issues with `PUSH` instructions, i tested it using `myth -d -c [bytecode]` as Bernhard told me and it seems to work. I can use it instead of `evm` if for you it is ok.

In this scenario i need to have `geth` installed and running only for using `Web3.sha3()` function, at this point i could use directly Web3 js library without constrain the user to have geth installed and running. Does it make sense for you ?
Thanks.
