### ISSUE TITLE
SWC-117 'Signature Malleability' fixed version fixes malleability but introduces DoS

### ISSUE THREAD

**Issue by rmi7** [SmartContractSecurity/SWC-registry#173]
While looking at the fixed version of SWC-117 Signature Malleability I noticed that it actually introduces a DoS.

Although signature malleability is fixed, the example introduces a DoS because of how signature replay is prevented.

And since people might be copying the signature related code for use in their own code, it would make sense that it's correct.

## Vulnerable version (only relevant parts)

```javascript
mapping(bytes32 => bool) signatureUsed;

function transfer(
  bytes _signature,
  address _to,
  uint256 _value,
  uint256 _gasPrice,
  uint256 _nonce
) public returns (bool) {
  // signature malleability is caused by next line
  bytes32 txid = keccak256(abi.encodePacked(getTransferHash(_to, _value, _gasPrice, _nonce), _signature));
  require(!signatureUsed[txid]);

  address from = recoverTransferPreSigned(_signature, _to, _value, _gasPrice, _nonce);

  require(balances[from] > _value);
  balances[from] -= _value;
  balances[_to] += _value;

  signatureUsed[txid] = true;
}

function recoverTransferPreSigned(
  bytes _sig,
  address _to,
  uint256 _value,
  uint256 _gasPrice,
  uint256 _nonce
) public view returns (address recovered) {
  return ecrecoverFromSig(getSignHash(getTransferHash(_to, _value, _gasPrice, _nonce)), _sig);
}

function getTransferHash(
  address _to,
  uint256 _value,
  uint256 _gasPrice,
  uint256 _nonce
) public view returns (bytes32 txHash) {
  return keccak256(address(this), bytes4(0x1296830d), _to, _value, _gasPrice, _nonce);
}

function getSignHash(bytes32 _hash) public pure returns (bytes32 signHash) {
  return keccak256("\x19Ethereum Signed Message:\n32", _hash);
}
```

## Current "fixed" version (only updated parts)

```javascript
function transfer(
  bytes _signature,
  address _to,
  uint256 _value,
  uint256 _gasPrice,
  uint256 _nonce
) public returns (bool) {
  // signature malleability is fixed by the following updated line
  bytes32 txid = getTransferHash(_to, _value, _gasPrice, _nonce);
  require(!signatureUsed[txid]); // 💣💣💣 DoS is caused by this line

  address from = recoverTransferPreSigned(_signature, _to, _value, _gasPrice, _nonce);

  require(balances[from] > _value);
  balances[from] -= _value;
  balances[_to] += _value;

  signatureUsed[txid] = true;
}
```

## Problem Description

The fixed version prevents signature malleability. It however also introduces a DoS.

Since the first 2 lines of the "fixed" `transfer` function are:

```javascript
bytes32 txid = getTransferHash(_to, _value, _gasPrice, _nonce);
require(!signatureUsed[txid]);
```

And `getTransferHash` returns:

```javascript
keccak256(address(this), bytes4(0x1296830d), _to, _value, _gasPrice, _nonce);
```

If Alice sends `1` token to `0xdeadbeef` with gasPrice `1` and nonce `1`.
No other pre-signed transaction with these same arguments can be executed in the future by calling this `transfer` function.

Put otherwise, once a combination of `_to` + `value` + `_gasPrice` + `_nonce` has been used,
that same combination of arguments can never again be executed through `transfer`. no matter which "signer" sends the transaction or which `_signature` is used with the transaction.

## Possible fix

Instead of preventing signature replay by keeping track of every `keccack256(address(this), bytes4(0x1296830d), _to, _value, _nonce, _gasPrice)` that has been used.

Keep track of each `_nonce` used by a `from` and only allow a new signed transaction if its `_nonce` is 1 higher than the last used `_nonce`.

```javascript
// instead of: mapping(bytes32 => bool) signatureUsed;
mapping(address => uint) lastNonceUsed;

function transfer(
  bytes _signature,
  address _to,
  uint256 _value,
  uint256 _gasPrice,
  uint256 _nonce
) public returns (bool) {
  address from = recoverTransferPreSigned(_signature, _to, _value, _gasPrice, _nonce);

  // prevent overflow in case somebody 'from' manages to send max(uint256) 
  // pre-signed transactions through this function, if ever even possible..
  // max(uint256) = 115792089237316195423570985008687907853269984665640564039457584007913129639935
  require(lastNonceUsed[from] + 1 > lastNonceUsed[from]); 

  require(_nonce == lastNonceUsed[from] + 1);

  require(balances[from] > _value);
  balances[from] -= _value;
  balances[_to] += _value;

  lastNonceUsed[from] = _nonce;
}
```

**Comment by thec00n** [comment]
Hey @rmi7. Good observation, this could indeed be an annoying problem if you implement the replay protection like in the fixed version of the test case. The proposed replay protection with the nonces I find also more elegant than with the hashes. 

I also just noticed that `balances[_to] += _value;` could overflow as well ... Do you want to open a PR   to fix the issues?

**Comment by rmi7** [comment]
Hi @thec00n, I also noticed the overflow but thought that since it has nothing to do with signatures to just leave it there. 

I can make a PR yes (also fixing the overflow), which branch to point it to?

**Comment by thec00n** [comment]
`master` and if you don't mind could you change the compiler to 0.5.x and regenerate the JSON for both the fixed and vulnerable version. It be great to get more test cases in there that are compiled with more recent version of Solidity.

**Comment by rmi7** [comment]
Not as easy as it appears to be since with the proposed fix the example wont make sense anymore,

the fixed version deals with checking for signature replay differently than the "vulnerable" version.

So if you ask me the entire example code needs to changed, but not sure what the new version should be then.

looking forward to any input

**Comment by pvienhage** [comment]
Hi @rmi I fixed this is my production version of meta transaction libraries by adding a salt. This is better for two reasons (1) salting increses throughout by not enforcing ordering and (2) clients with salts don't need to access the blockchain to check the nonce.
I can add that solution to the dos if you like.

**Comment by rmi7** [comment]
Hi @pvienhage, i agree that would further improve the solution, no need for incrementing nonce + fetch-my-latest-nonce.

But this leaves open the question about the example used in the for SWC117. If we update the solution with the (non)incremeneting nonce check, then the sample doesn't make sense anymore if you ask me.

**Comment by rmi7** [comment]
@pvienhage you mean like this:

```javascript
// instead of: mapping(bytes32 => bool) signatureUsed;
mapping(address => mapping(uint256 => bool)) saltsUsed;

function transfer(
  bytes _signature,
  address _to,
  uint256 _value,
  uint256 _gasPrice,
  uint256 _salt
) public returns (bool) {
  address from = recoverTransferPreSigned(_signature, _to, _value, _gasPrice, _salt);
 
  require(!saltsUsed[from][_salt]);
  
  require(balances[from] > _value);

  balances[from] -= _value;
  balances[_to] += _value;

  saltsUsed[from][_salt] = true
}
```

**Comment by pvienhage** [comment]
Hi, @rmi7 glad you think it would improve it. Also what you had posted isn't quite what I meant, instead you can hash the salt into the txid with the rest of the data and use the same code as the current fixed version.

**Comment by rmi7** [comment]
so instead of:

```javascript
bytes32 txid = getTransferHash(_to, _value, _gasPrice, _nonce);`
```

do:

```javascript
bytes32 txid = getTransferHash(_to, _value, _gasPrice, _salt);`
```

or put otherwise, assuming `_nonce` acts as a salt (meaning a random uint256), the original code will work.

**Comment by rmi7** [comment]
then I conclude this is a non-issue, as long as the `nonce` is a random number instead of an incrementing number starting at 0 (or some other predictable starting point), if you agree @thec00n we can close this issue.
