### ISSUE TITLE
Please add unprotected ᴇʀᴄ‑20 token withdrawal !

### ISSUE THREAD

**Issue by ytrezq** [SmartContractSecurity/SWC-registry#213]
The exact copy of ꜱᴡᴄ 105 but with tokens.

This is especially meanfull with Wrapped Ether being the de‑facto official Ethereum to ᴇʀᴄ‑20 wrapper and tokens that will always bear value like soft pegged to gold tokens.

**Comment by maurelian** [comment]
PRs welcome. :)

**Comment by maurelian** [comment]
Though it might make more sense to simply expand SWC-105 to include tokens.

**Comment by chaals** [comment]
If this repo were maintained it would make sense to add this to SWC-105 (even just a note clarifying that it applies there too would do the trick). But it's not really maintained anymore, superseded by https://entethalliance.org/specs/ethtrust-sl since at least last year.
