### ISSUE TITLE
Please add ꜱᴡᴄ for case where attacker is a able to pass hash directly to ecrecover !

### ISSUE THREAD

**Issue by ytrezq** [SmartContractSecurity/SWC-registry#214]
If verifier contract doesn’t hash a message itself and the hash doesn’t require a pre‑image, then there’s a problem similar but different from signature malleability described [here](https://yondon.blog/2019/01/01/how-not-to-use-ecdsa/ "scroll down the page to the bottom as the description is in part #2").

**Comment by maurelian** [comment]
LGTM. It's Pitfall #2 at that URL.

**Comment by chaals** [comment]
This repo is no longer maintained, and we are not adding new SWCs (has probably become obvious since this was filed).

So closing this as "won't get fixed"
