### ISSUE TITLE
Ensure SWC numbers are assigned continuously in CI

### ISSUE THREAD

**Issue by enderphan94** [SmartContractSecurity/SWC-registry#215]
I don't see the SWC-126 on the website. What's the reason?

https://swcregistry.io/docs/SWC-126

**Comment by maurelian** [comment]
Using the git methods listed [here](https://stackoverflow.com/questions/953481/find-and-restore-a-deleted-file-in-a-git-repository), it looks like it never existed, and was skipped by accident. 

Perhaps the next SWC to be added should have that number?

**Comment by thec00n** [comment]
@maurelian @enderphan94 if I recall correctly we had multiple PRs for a new SWC categories at some point and I think one of them then did not make it in. I think we should have documentation around the review process and at which point a SWC id gets assigned. We can assign 126 to next category that gets accepted?

**Comment by enderphan94** [comment]
@thec00n  Sounds great! I'm waiting for the 126 back to the list :)

**Comment by maurelian** [comment]
Seems like an easy check to run on PRs in CI.

**Comment by chaals** [comment]
This repo is not actively maintained, having been superseded by at least the [EEA EthTrust Security Levels Specification](https://entethalliance.org/specs/ethtrust-sl) (probably other stuff is more developed now too). So this isn't likely to happen.
