### ISSUE TITLE
Hash collisions when using abi.encodePacked() with multiple variable length arguments

### ISSUE THREAD

**Issue by maurelian** [SmartContractSecurity/SWC-registry#217]
Can provide more detail in the future.

**Comment by maurelian** [comment]
More info (full credit to @smarx for the following text) 
Still trying to find a better example, but the last version of this bug we spotted in an audit looked something like this:

```solidity
contract AccessControl {
    using ECDSA for bytes32;
    mapping(address => bool) isAdmin;
    mapping(address => bool) isRegularUser;
    // Add admins and regular users.
    function addUsers(
        address[] calldata admins,
        address[] calldata regularUsers,
        bytes calldata signature
    )
        external
    {
        if (!isAdmin[msg.sender]) {
            // Allow calls to be relayed with an admin's signature.
            bytes32 hash = keccak256(abi.encodePacked(admins, regularUsers));
            address signer = hash.toEthSignedMessageHash().recover(signature);
            require(isAdmin[signer], "Only admins can add users.");
        }
        for (uint256 i = 0; i < admins.length; i++) {
            isAdmin[admins[i]] = true;
        }
        for (uint256 i = 0; i < regularUsers.length; i++) {
            isRegularUser[regularUsers[i]] = true;
        }
    }
}
```

A regular user can promote himself to admin. 

If you see `addUser([addr1, addr2], [addr3, <your address>, addr4], sig)`, you can call `addUser([addr1, addr2, addr3, <your address>], [addr4], sig)`. 

The signature will still match, and now you’re an admin.

Often there’s replay protection, so an attacker has to front run. But in this example, `addUsers()` is idempotent, so there’s no need for replay protection.

**Comment by KadenZipfel** [comment]
What's the source/author for this `AccessControl` contract?

**Comment by smarx** [comment]
Me. I made this up, though it's loosely based on an audit we did.

**Comment by KadenZipfel** [comment]
https://github.com/SmartContractSecurity/SWC-registry/pull/231
