### ISSUE TITLE
SWC-116 incorrectly suggests using block.number as a proxy for time

### ISSUE THREAD

**Issue by KadenZipfel** [SmartContractSecurity/SWC-registry#234]
https://swcregistry.io/docs/SWC-116

In the remediation section it is suggested to use `block.number` instead of `block.timestamp`, however, `block.number` is not more precise than `block.timestamp`.

**Comment by maurelian** [comment]
yeah... this is a hard topic, but I agree that `timestamp` is less error prone, and it matches the BP guidance: https://consensys.github.io/smart-contract-best-practices/recommendations/#timestamp-dependence

@b-mueller @thec00n do we have a way of deprecating swcs?

**Comment by maurelian** [comment]
Can we close this per https://github.com/SmartContractSecurity/SWC-registry/pull/232#issuecomment-574845274?

**Comment by KadenZipfel** [comment]
Yep
