### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by pi3ch** [SmartContractSecurity/SWC-registry#275]
They are quite a few pull requests waiting and issues open. Anyone still looking after this project?

I hope it is still alive because it is one of the cleanest reference I've found.

**Comment by thec00n** [comment]
There are currently no core contributors that can triage and merge new content.

**Comment by thec00n** [comment]
see https://github.com/SmartContractSecurity/SWC-registry/issues/276

**Comment by chaals** [comment]
This is not really maintained. I have access and am slowly churning through open issues / PRs, but this is superseded by (among other things I guess) the [EEA EthTrust Security Levels specification](https://entethalliance.org/specs/ethtrust-sl/) since at least 2022.
