### ISSUE TITLE
More automated way to create a test case

### ISSUE THREAD

**Issue by rocky** [SmartContractSecurity/SWC-registry#53]
The README has instructions for creating a test case which could be put into a shell script. 

However more work is needed and this might include creating a template YAML file. 

Even better would be a combination like "swe-test-case init *directory*" and swe-test-case compile *testcase*.

**Comment by chaals** [comment]
This repo isn't maintained anymore - it has been superseded at least by the [EEA EthTrust Security Levels Specification](https://entethalliance.org/specs/ethtrust-sl/) so this is unlikely to happen.
