### ISSUE TITLE
Update website header/footer

### ISSUE THREAD

**Issue by s0b0lev** [SmartContractSecurity/SWC-registry#59]
### Update footer

![footer](https://user-images.githubusercontent.com/2613381/45938995-fd729000-bff0-11e8-911b-10e3ce32ccf8.png)

**Comment by thec00n** [comment]
**Header:**

On the Left: 

Rename SWC-registry to "Overview"

On the Right: 
Rename Docs to "Registry"

**Footer:**

Docs:
- How to add a SWC definition (https://smartcontractsecurity.github.io/SWC-registry/#create-a-new-swc-entry)
- How to add a test case (https://smartcontractsecurity.github.io/SWC-registry/#create-a-test-case)
- EIP XXXX (Link to the EIP)

Community: 
- Join the [Discord channel](https://discord.gg/qcNvR2r) #swc-registry 
- Discussion at the Ethereum Magicians 

More:
- Back to SWC-registry repo (Link https://github.com/SmartContractSecurity/SWC-registry/)
 
- Remove the facebook thing

**Comment by s0b0lev** [comment]
PR merged: https://github.com/SmartContractSecurity/SWC-registry/pull/71

**Comment by b-mueller** [comment]
@thec00n @s0b0lev suggested edits for the introduction paragraph:

"The following table contains an overview of the SWC registry. Each row consists of an SWC identifier (ID), weakness title, CWE parent and list of related code samples. The links in the "ID" and "test cases" columms lead to details about the respective SWC. Links in the "Base/Class" columns lead to the CWE Base or Class type."

**Comment by s0b0lev** [comment]
@thec00n do we need anything else to be done for this issue?
