### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by s0b0lev** [SmartContractSecurity/SWC-registry#83]
Docusaurus use hljs.
Research a way to highlight solidity code

https://docusaurus.io/docs/en/doc-markdown#registering-additional-languages

**Comment by ersul4ik** [comment]
I learned that there is a 'highlightjs-solidity', but I don’t understand if it will suit us

**Comment by s0b0lev** [comment]
Issue with Docusaurus:
https://github.com/facebook/Docusaurus/issues/960

![local](https://user-images.githubusercontent.com/2613381/46423384-3bda1e80-c758-11e8-9b2a-798a46518531.png)
![prod](https://user-images.githubusercontent.com/2613381/46423388-3da3e200-c758-11e8-827f-1eccbc125d5d.png)
