### ISSUE TITLE
Add a link back to the Github repo in the SWC pages header

### ISSUE THREAD

**Issue by thec00n** [SmartContractSecurity/SWC-registry#93]
Similar to the Smart Contract Best Practices. 

![screen shot 2018-10-10 at 11 32 00 am](https://user-images.githubusercontent.com/6027459/46711760-44fb4c00-cc80-11e8-9e39-2d8b8c193fc2.png)

**Comment by ersul4ik** [comment]
Added link with configure siteConfig file.
